# Generated by Django 5.1.6 on 2025-02-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_student_reset_token'),
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('student', 'skill')},
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill_proficiency',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill_type',
            field=models.CharField(choices=[('teach', 'Teach'), ('learn', 'Learn'), ('volunteer', 'Volunteer')], max_length=15),
        ),
    ]
