# Generated by Django 5.1.6 on 2025-02-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_student_reset_token'),
        ('Core', '0002_alter_userskill_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('student', 'skill', 'skill_type')},
        ),
    ]
