# Generated by Django 5.1.6 on 2025-02-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
