# Generated by Django 5.1.6 on 2025-03-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_student_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_pic',
            name='image',
            field=models.ImageField(blank=True, default='static/images/default-profile.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
